routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('a-propos-de-nous', [HomeController::class, 'apropos'])->name('apropos');
Route::get('contact', [HomeController::class, 'contact'])->name('contact');
Route::get('services', [HomeController::class, 'services'])->name('services');


Route::resource('categories', CategoryController::class)
                                    ->names('categories');

Route::resource('posts', PostController::class)->names("posts");

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    protected  $fillable = ['name'];

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'image',
        'date_pub',
        'author',
        'status',
        'category_id'
    ];

    /**
     * Cette fonction permet de récupérer
     * la catégory d'un article
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::all();

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required'
        ]);
        
        Category::create($validated);

        return redirect()->route('categories.index')
        ->with('success', 'Catégorie ajouté avec succès!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Category $category)
    {
        $validated = $request->validate([
            'name' => 'required',
        ]);
        $category->update($validated);

        return to_route('categories.index')
                ->with('success', 'Catégorie modifié avec succès!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return back()
        ->with('success', 'Catégorie supprimé avec succès !');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function home(){
        return view('home');
    }

    public function apropos(){
        return view('apropos');
    }

    public function contact(){
        return view('contact');
    }

    public function services(){
        return view('services');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = Post::where("status",true)
                        ->orderBy("id", "DESC")
                        ->paginate(12);

        //dd($posts);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //récupération de toutes les catégories
        $categories = Category::all();

        return view('posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required',
            'description' => '',
            'image' => 'image|mimes:png,jpg,jpeg,gif,svg|max:2048',
            'date_pub' => '',
            'author' => '',
            'status' => 'required',
            'category_id' => "required"
        ]);

        //Uploder l'image sur le server
        $imageName = time().'.'.$request->image->extension();
        $request->image->move(public_path('images'), $imageName);

        $validated['image'] = $imageName;

        Post::create($validated);

        return back()
        ->with('success', 'Article créé avec succès !');
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/apropos.blade.php
@extends('layouts.app')

@section("title", "A propos de nous")

@section("content")
    <h3>A propos de nous</h3>
@endsection

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('title', "Ajout d'une catégorie")

@section("content")
    <div class="row">
        <h3>Formulaire de création d'une catégorie</h3>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('categories.store') }}" method="post">
            @csrf
            @include('categories.form')
            <div class="d-grip gap-2">
                <button type="submit" class="btn btn-primary">
                    Ajouter une catégorie
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends("layouts.app")

@section("title", "Modification d'une catégorie")

@section("content")
    <div class="row">
        <h3>Modification d'une catégorie</h3>
        <form 
        action="{{ route("categories.update", $category->id) }}" 
        method="post">
        
            @csrf
            @method("PUT")

            @include("categories.form")
            
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-warning">
                    Enregistrer la catégorie
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/categories/form.blade.php
<div class="form-group mb-3">
    <label for="name">
        Nom de votre catégorie :
    </label>
    <input 
    value="@isset($category->name){{ $category->name }}@endisset"
    required type="text" name="name" class="form-control">
</div>

resources/views/categories/index.blade.php
@extends('layouts.app')

@section("title", "La liste des catégories d'article")

@section("content")
    <div class="row">
        <h3>Liste des catégories</h3>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{{ route('categories.create') }}" 
                class="btn btn-primary">
                Nouvelle catégorie
            </a>
        </div>
        @if (Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom de la catégorie</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                    <tr>
                        <td>{{ $category->name }}</td>
                        <td style="display: flex">
                            <a 
                                class="btn btn-warning btn-sm" style="margin-right: 5px"
                                href="{{ route("categories.edit", $category->id) }}">
                                Modifier
                            </a>

                            <form action="{{ route('categories.destroy',$category->id) }}" method="post">
                                @csrf
                                @method("DELETE")
                                <input onclick="return confirm('Êtes-vous sûr ?')" 
                                class="btn btn-danger btn-sm" 
                                    type="submit" value="Supprimer">
                            </form>

                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/contact.blade.php
@extends("layouts.app")

@section("title", "Pade de contact")

@section("content")
    <h3>Formulaire de contact</h3>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Bienvenue sur mon blog')

@section("content")
    <h3>Page d'accueil</h3>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <header>
        @include('layouts.header')
    </header>
    <main class="container mt-3">
        @yield('content')
    </main>
    <footer>

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-lg bg-warning" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ route('home') }}">Mon Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ route('home') }}">Accueil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('apropos') }}">A propos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route("categories.index") }}">
              Gestion des catégories
            </a>
          </li>
          
          
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Search">
          <button class="btn btn-success" type="submit">Rechercher</button>
        </form>
      </div>
    </div>
  </nav>

resources/views/posts/create.blade.php
@extends("layouts.app")

@section("title", "Nouvel article")

@section("content")
    <div class="row">
        <h3>Nouvel article</h3>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if (Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
        <form enctype="multipart/form-data" 
            action="{{ route('posts.store') }}" method="post">
            @csrf
            @include("posts.form")
            
            <div class="d-grid gap-2 mb-3">
                <button type="submit" class="btn btn-primary">
                    Ajouter un article
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/posts/form.blade.php
<div class="form-group mb-3">
    <label for="title">Titre de l'article : </label>
    <input type="text" name="title" class="form-control">
</div>
<div class="from-group mb-3">
    <label for="description">Description de l'article :</label>
    <textarea name="description" class="form-control"></textarea>
</div>
<div class="from-group mb-3">
    <label for="image">Image de l'article</label>
    <input type="file" name="image" class="form-control">
</div>
<div class="from-group mb-3">
    <label for="date_pub">
        Date de publication de l'article 
    </label>
    <input type="date" name="date_pub" class="form-control">
</div>
<div class="from-group mb-3">
    <label for="author">Auteur de l'article</label>
    <input type="text" name="author" class="form-control">
</div>
<div class="form-group mb-3">
    <label for="category">Catégorie de l'article</label>
    <select name="category_id" class="form-select">
        <option>Choisir une catégorie</option>
        @foreach ($categories as $category)
            <option value="{{ $category->id }}">
                {{ $category->name }}
            </option>
        @endforeach
    </select>
</div>
<div class="from-group mb-3">
    <label for="status">Statut de l'article</label>
    <select name="status" class="form-select">
        <option value="1">Publié</option>
        <option value="0">Non publié</option>
    </select>
</div>

resources/views/posts/index.blade.php
@extends('layouts.app')

@section("title", "La liste des articles")

@section("content")
    <div class="row">
        <h3>La liste des articles</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Titre</th>
                    <th>Date de publication</th>
                    <th>Auteur</th>
                    <th>Catégorie</th>
                    <th>Statut</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                    <tr>
                        <td>
                            <img width="50" class="img-thumbnail"
                            src="{{ asset('images/'.$post->image) }}" alt="">
                        </td>
                        <td>
                            <strong>{{ $post->title }}</strong>
                        </td>
                        <td>{{ $post->date_pub }}</td>
                        <td>{{ $post->author }}</td>
                        <td>{{ $post->category->name }}</td>
                        <td>
                            @if ($post->status == 1)
                                <span class="badge text-bg-success">
                                    Publié
                                </span>
                                @else
                                <span class="badge text-bg-danger">
                                    Non Publié
                                </span>
                            @endif
                        </td>
                        <td style="display: flex">
                            <a class="btn btn-primary btn-sm"
                            style="margin-right: 5px"
                                href="{{ route('posts.show',$post->id) }}">
                                Détail
                            </a>

                            <a class="btn btn-warning btn-sm"
                            style="margin-right: 5px"
                                href="{{ route('posts.edit',$post->id) }}">
                                Modifier
                            </a>

                            <form action="{{ route('posts.destroy',$post->id) }}" 
                                method="post">
                                <input onclick="return confirm('Êtes-vous sûr?')"
                                class="btn btn-sm btn-danger" 
                                type="submit" value="Supprimer">
                            </form>

                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div class="pagination">
            {{ $posts->links() }}
        </div>
    </div>
@endsection

resources/views/services.blade.php
@extends('layouts.app')

@section("title", "Mes services")

@section("content")
    <h3>Mes services</h3>
@endsection